name: Latest Blogs
on:
  schedule:
    # Runs every hour
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  update-latest-blogs:
    name: Update this repo's README with latest blogs from Medium
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: gautamkrishnar/blog-post-workflow@master
        with:
          comment_tag_name: "MY-LATEST-BLOGS-LIST"
          feed_list: "https://medium.com/feed/@sparmeet162000"
